version: '3.8'

services:
  app:
    image: webdevops/php-nginx:8.3
    container_name: laravel_train
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html/public
    working_dir: /var/www/html
    depends_on:
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql_train
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_train
    ports:
      - "8089:80"
    environment:
      PMA_HOST: mysql_train
      PMA_USER: root
      PMA_PASSWORD:
    depends_on:
      - mysql
    networks:
      - laravel

  maildev:
    image: maildev/maildev
    container_name: maildev_train
    ports:
      - "1088:1080"
      - "1025:1025"
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
